DELETE FROM IMPORTXMLTOTD.WAFFLES;
DELETE FROM IMPORTXMLTOTD.TOAST;
DELETE FROM IMPORTXMLTOTD.HOMESTYLE;
DELETE FROM IMPORTXMLTOTD.ESPRESSO;
DELETE FROM IMPORTXMLTOTD.FRAPPUCCINO;
DELETE FROM IMPORTXMLTOTD.TEA;
DELETE FROM IMPORTXMLTOTD.CHOCOLATE;