--<ScriptOptions statementTerminator=";"/>

-- data tables
DROP TABLE $DATABASE.WAFFLES;
DROP TABLE $DATABASE.WAFFLES_TMP;
DROP TABLE $DATABASE.TOAST;
DROP TABLE $DATABASE.TOAST_TMP;
DROP TABLE $DATABASE.HOMESTYLE;
DROP TABLE $DATABASE.HOMESTYLE_TMP;
DROP TABLE $DATABASE.ESPRESSO;
DROP TABLE $DATABASE.ESPRESSO_TMP;
DROP TABLE $DATABASE.FRAPPUCCINO;
DROP TABLE $DATABASE.FRAPPUCCINO_TMP;
DROP TABLE $DATABASE.TEA;
DROP TABLE $DATABASE.TEA_TMP;
DROP TABLE $DATABASE.CHOCOLATE;
DROP TABLE $DATABASE.CHOCOLATE_TMP;

CREATE MULTISET TABLE $DATABASE.WAFFLES ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Name VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRICE DECIMAL(10,2),
      Description VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      Srcfile VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      LOADTIMESTAMP TIMESTAMP(0))
NO PRIMARY INDEX ;

CREATE MULTISET TABLE $DATABASE.WAFFLES_TMP ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Name VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Price VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Description VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      SRCFILE VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC)
NO PRIMARY INDEX ;

CREATE MULTISET TABLE $DATABASE.TOAST ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Name VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRICE DECIMAL(10,2),
      Description VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      Srcfile VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      LOADTIMESTAMP TIMESTAMP(0))
NO PRIMARY INDEX ;

CREATE MULTISET TABLE $DATABASE.TOAST_TMP ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Name VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Price VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Description VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      SRCFILE VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC)
NO PRIMARY INDEX ;

CREATE MULTISET TABLE $DATABASE.HOMESTYLE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Name VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRICE DECIMAL(10,2),
      Description VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      Srcfile VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      LOADTIMESTAMP TIMESTAMP(0))
NO PRIMARY INDEX ;

CREATE MULTISET TABLE $DATABASE.HOMESTYLE_TMP ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Name VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Price VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Description VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      SRCFILE VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC)
NO PRIMARY INDEX ;

CREATE MULTISET TABLE $DATABASE.ESPRESSO ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Name VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRICE DECIMAL(10,2),
      Description VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      Srcfile VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      LOADTIMESTAMP TIMESTAMP(0))
NO PRIMARY INDEX ;

CREATE MULTISET TABLE $DATABASE.ESPRESSO_TMP ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Name VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Price VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Description VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      SRCFILE VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC)
NO PRIMARY INDEX ;

CREATE MULTISET TABLE $DATABASE.FRAPPUCCINO ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Name VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRICE DECIMAL(10,2),
      Description VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      Srcfile VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      LOADTIMESTAMP TIMESTAMP(0))
NO PRIMARY INDEX ;

CREATE MULTISET TABLE $DATABASE.FRAPPUCCINO_TMP ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Name VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Price VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Description VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      SRCFILE VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC)
NO PRIMARY INDEX ;

CREATE MULTISET TABLE $DATABASE.TEA ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Name VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRICE DECIMAL(10,2),
      Description VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      Srcfile VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      LOADTIMESTAMP TIMESTAMP(0))
NO PRIMARY INDEX ;

CREATE MULTISET TABLE $DATABASE.TEA_TMP ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Name VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Price VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Description VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      SRCFILE VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC)
NO PRIMARY INDEX ;

CREATE MULTISET TABLE $DATABASE.CHOCOLATE ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Name VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      PRICE DECIMAL(10,2),
      Description VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      Srcfile VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      LOADTIMESTAMP TIMESTAMP(0))
NO PRIMARY INDEX ;

CREATE MULTISET TABLE $DATABASE.CHOCOLATE_TMP ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Name VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Price VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      Description VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      SRCFILE VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC)
NO PRIMARY INDEX ;


-- summary tables
DROP TABLE $DATABASE.XMLTOTD_SUMMARY;

DROP TABLE $DATABASE.XMLTOTD_SUMMARY_TMP;

CREATE MULTISET TABLE $DATABASE.XMLTOTD_SUMMARY_TMP ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      START_DATETIME VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      ELAPSED_RUNTIME VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      LOG_FILENAME VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      DESCRIPTION VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC)
NO PRIMARY INDEX ;

CREATE MULTISET TABLE $DATABASE.XMLTOTD_SUMMARY ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LOG_ID DECIMAL(38,0) NOT NULL GENERATED ALWAYS AS IDENTITY
           (START WITH 1
            INCREMENT BY 1
            MINVALUE 1
            MAXVALUE 999999999999999999
            NO CYCLE),
      START_DATETIME VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      ELAPSED_RUNTIME VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      LOG_FILENAME VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC,
      DESCRIPTION VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( LOG_ID );